# conda env create -f environment.yml
# conda activate sdg-11wind
name: sdg-11wind
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - scipy
  - requests
  - xarray
  - netcdf4
  - matplotlib
  - plotly
  - folium
  - branca
  - pip
  - pip:
      - cdsapi>=0.7.7
